// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('current_password_empty', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('current_password_empty', async function() {
    // Test name: current_password_empty
    // Step # | name | target | value
    // 1 | open | http://localhost:5173/ | 
    await driver.get("http://localhost:5173/")
    // 2 | setWindowSize | 1062x804 | 
    await driver.manage().window().setRect({ width: 1062, height: 804 })
    // 3 | click | linkText=Sign In | 
    await driver.findElement(By.linkText("Sign In")).click()
    // 4 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 5 | type | name=email | zeelghorij@gmail.com
    await driver.findElement(By.name("email")).sendKeys("zeelghorij@gmail.com")
    // 6 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 7 | type | name=password | Password123New
    await driver.findElement(By.name("password")).sendKeys("Password123New")
    // 8 | click | css=.fi-rr-eye-crossed | 
    await driver.findElement(By.css(".fi-rr-eye-crossed")).click()
    // 9 | click | css=.mt-14 | 
    await driver.findElement(By.css(".mt-14")).click()
    // 10 | mouseOver | css=.w-12:nth-child(3) | 
    {
      const element = await driver.findElement(By.css(".w-12:nth-child(3)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 11 | click | css=.w-12 > .w-full | 
    await driver.findElement(By.css(".w-12 > .w-full")).click()
    // 12 | click | linkText=Settings | 
    await driver.findElement(By.linkText("Settings")).click()
    // 13 | click | linkText=Change Password | 
    await driver.findElement(By.linkText("Change Password")).click()
    // 14 | click | name=newPassword | 
    await driver.findElement(By.name("newPassword")).click()
    // 15 | type | name=newPassword | New123Password
    await driver.findElement(By.name("newPassword")).sendKeys("New123Password")
    // 16 | click | css=.relative:nth-child(2) > .fi-rr-eye-crossed | 
    await driver.findElement(By.css(".relative:nth-child(2) > .fi-rr-eye-crossed")).click()
    // 17 | click | css=.btn-dark | 
    await driver.findElement(By.css(".btn-dark")).click()
    // 18 | click | name=currentPassword | 
    await driver.findElement(By.name("currentPassword")).click()
    // 19 | type | name=currentPassword | Password123New
    await driver.findElement(By.name("currentPassword")).sendKeys("Password123New")
    // 20 | click | css=.fi-rr-eye-crossed | 
    await driver.findElement(By.css(".fi-rr-eye-crossed")).click()
    // 21 | click | css=.btn-dark | 
    await driver.findElement(By.css(".btn-dark")).click()
    // 22 | click | css=.flex-none > .w-20 | 
    await driver.findElement(By.css(".flex-none > .w-20")).click()
  })
})
