// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('search without login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('search without login', async function() {
    // Test name: search without login
    // Step # | name | target | value | comment
    // 1 | open | https://connectco.netlify.app/ |  | 
    await driver.get("https://connectco.netlify.app/")
    // 2 | setWindowSize | 1398x792 |  | 
    await driver.manage().window().setRect({ width: 1398, height: 792 })
    // 3 | click | css=.pl-6 |  | 
    await driver.findElement(By.css(".pl-6")).click()
    // 4 | type | css=.pl-6 | autumn | 
    await driver.findElement(By.css(".pl-6")).sendKeys("autumn")
    // 5 | sendKeys | css=.pl-6 | ${KEY_ENTER} | 
    await driver.findElement(By.css(".pl-6")).sendKeys(Key.ENTER)
    // 6 | click | css=div:nth-child(3) .gap-4 |  | 
    await driver.findElement(By.css("div:nth-child(3) .gap-4")).click()
    // 7 | close |  |  | 
    await driver.close()
  })
})
