// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Search and Browsing ', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Search and Browsing ', async function() {
    await driver.get("https://connectco.netlify.app/")
    await driver.manage().window().setRect({ width: 1296, height: 688 })
    await driver.findElement(By.linkText("Sign In")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("pareshpatel@gmail.com")
    await driver.findElement(By.name("password")).sendKeys("Paresh123")
    await driver.findElement(By.css(".mt-14")).click()
    await driver.findElement(By.css(".pl-6")).click()
    await driver.findElement(By.css(".pl-6")).sendKeys("google")
    await driver.findElement(By.css(".pl-6")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".w-12 > .w-full")).click()
    await driver.findElement(By.css(".text-left > .text-dark-grey")).click()
    await driver.findElement(By.css(".min-w-\\[40\\%\\]")).click()
    {
      const element = await driver.findElement(By.css(".min-w-\\[40\\%\\]"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
  })
})
