// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Incorrect_New_password', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Incorrect_New_password', async function() {
    // Test name: Incorrect_New_password
    // Step # | name | target | value
    // 1 | open | http://localhost:5173/ | 
    await driver.get("http://localhost:5173/")
    // 2 | setWindowSize | 1060x804 | 
    await driver.manage().window().setRect({ width: 1060, height: 804 })
    // 3 | click | css=.fi-rr-moon-stars | 
    await driver.findElement(By.css(".fi-rr-moon-stars")).click()
    // 4 | click | linkText=Sign In | 
    await driver.findElement(By.linkText("Sign In")).click()
    // 5 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 6 | type | name=email | zeelghorij@gmail.com
    await driver.findElement(By.name("email")).sendKeys("zeelghorij@gmail.com")
    // 7 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 8 | type | name=password | Password123New
    await driver.findElement(By.name("password")).sendKeys("Password123New")
    // 9 | click | css=.fi-rr-eye-crossed | 
    await driver.findElement(By.css(".fi-rr-eye-crossed")).click()
    // 10 | click | css=.mt-14 | 
    await driver.findElement(By.css(".mt-14")).click()
    // 11 | mouseOver | css=.fi-rr-bell | 
    {
      const element = await driver.findElement(By.css(".fi-rr-bell"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 12 | click | css=.w-12 > .w-full | 
    await driver.findElement(By.css(".w-12 > .w-full")).click()
    // 13 | click | linkText=Settings | 
    await driver.findElement(By.linkText("Settings")).click()
    // 14 | click | linkText=Change Password | 
    await driver.findElement(By.linkText("Change Password")).click()
    // 15 | click | name=currentPassword | 
    await driver.findElement(By.name("currentPassword")).click()
    // 16 | type | name=currentPassword | Password123New
    await driver.findElement(By.name("currentPassword")).sendKeys("Password123New")
    // 17 | click | css=.relative:nth-child(1) > .fi-rr-eye-crossed | 
    await driver.findElement(By.css(".relative:nth-child(1) > .fi-rr-eye-crossed")).click()
    // 18 | click | name=newPassword | 
    await driver.findElement(By.name("newPassword")).click()
    // 19 | type | name=newPassword | Pass
    await driver.findElement(By.name("newPassword")).sendKeys("Pass")
    // 20 | click | css=.fi-rr-eye-crossed | 
    await driver.findElement(By.css(".fi-rr-eye-crossed")).click()
    // 21 | click | css=.btn-dark | 
    await driver.findElement(By.css(".btn-dark")).click()
    // 22 | click | name=newPassword | 
    await driver.findElement(By.name("newPassword")).click()
    // 23 | type | name=newPassword | Password
    await driver.findElement(By.name("newPassword")).sendKeys("Password")
    // 24 | click | css=.btn-dark | 
    await driver.findElement(By.css(".btn-dark")).click()
    // 25 | click | name=newPassword | 
    await driver.findElement(By.name("newPassword")).click()
    // 26 | type | name=newPassword | Password@12
    await driver.findElement(By.name("newPassword")).sendKeys("Password@12")
    // 27 | click | css=.btn-dark | 
    await driver.findElement(By.css(".btn-dark")).click()
  })
})
