// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('GetBlog without login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('GetBlog without login', async function() {
    // Test name: GetBlog without login
    // Step # | name | target | value | comment
    // 1 | open | https://connectco.netlify.app/ |  | 
    await driver.get("https://connectco.netlify.app/")
    // 2 | setWindowSize | 1398x792 |  | 
    await driver.manage().window().setRect({ width: 1398, height: 792 })
    // 3 | click | linkText=Write |  | 
    await driver.findElement(By.linkText("Write")).click()
  })
})
