// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('uploadblog', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('uploadblog', async function() {
    await driver.get("https://connectco.netlify.app/")
    await driver.manage().window().setRect({ width: 1296, height: 688 })
    {
      const element = await driver.findElement(By.linkText("Sign In"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Sign In")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("pareshpatel@gmail.com")
    await driver.findElement(By.name("password")).sendKeys("Paresh123")
    await driver.findElement(By.css(".mt-14")).click()
    await driver.findElement(By.css(".fi-rr-file-edit")).click()
    await driver.findElement(By.css(".z-20")).click()
    await driver.findElement(By.css(".text-4xl")).click()
    await driver.findElement(By.css(".text-4xl")).sendKeys("Autumn")
    await driver.findElement(By.css(".ce-paragraph")).click()
    {
      const element = await driver.findElement(By.css(".ce-paragraph"))
      await driver.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'Most beautiful winter'}", element)
    }
    await driver.findElement(By.css(".btn-dark")).click()
    await driver.findElement(By.css(".h-40")).click()
    await driver.findElement(By.css(".h-40")).sendKeys("helloo")
    await driver.findElement(By.css(".sticky")).click()
    await driver.findElement(By.css(".sticky")).sendKeys("nature")
    await driver.findElement(By.css(".sticky")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".btn-dark")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".w-12 > .w-full")).click()
    await driver.findElement(By.css(".w-12 > .w-full")).click()
    await driver.findElement(By.css(".font-bold")).click()
    await driver.findElement(By.css("html")).click()
    {
      const element = await driver.findElement(By.css("html"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".h-cover")).click()
  })
})
