// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login invalid password', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login invalid password', async function() {
    // Test name: login invalid password
    // Step # | name | target | value
    // 1 | open | http://localhost:5173/ | 
    await driver.get("http://localhost:5173/")
    // 2 | setWindowSize | 1218x816 | 
    await driver.manage().window().setRect({ width: 1218, height: 816 })
    // 3 | click | linkText=Sign In | 
    await driver.findElement(By.linkText("Sign In")).click()
    // 4 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 5 | type | name=email | crn7forlife@gmail.com
    await driver.findElement(By.name("email")).sendKeys("crn7forlife@gmail.com")
    // 6 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 7 | type | name=password | adi4
    await driver.findElement(By.name("password")).sendKeys("adi4")
    // 8 | click | css=.mt-14 | 
    await driver.findElement(By.css(".mt-14")).click()
  })
})
