// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login incorrect password', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login incorrect password', async function() {
    // Test name: login incorrect password
    // Step # | name | target | value
    // 1 | open | http://localhost:5173/ | 
    await driver.get("http://localhost:5173/")
    // 2 | setWindowSize | 1218x816 | 
    await driver.manage().window().setRect({ width: 1218, height: 816 })
    // 3 | mouseOver | linkText=Sign Up | 
    {
      const element = await driver.findElement(By.linkText("Sign Up"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 4 | mouseOut | linkText=Sign Up | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 5 | click | linkText=Sign In | 
    await driver.findElement(By.linkText("Sign In")).click()
    // 6 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 7 | type | name=email | crn
    await driver.findElement(By.name("email")).sendKeys("crn")
    // 8 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 9 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 10 | type | name=email | crn7forlife@gmail.com
    await driver.findElement(By.name("email")).sendKeys("crn7forlife@gmail.com")
    // 11 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 12 | type | name=password | Adity123
    await driver.findElement(By.name("password")).sendKeys("Adity123")
    // 13 | click | css=.mt-14 | 
    await driver.findElement(By.css(".mt-14")).click()
    // 14 | close |  | 
    await driver.close()
  })
})
