// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('KeywordSearching', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('KeywordSearching', async function() {
    await driver.get("https://connectco.netlify.app/")
    await driver.manage().window().setRect({ width: 786, height: 816 })
    await driver.findElement(By.css(".pl-6")).click()
    await driver.findElement(By.css(".pl-6")).click()
    await driver.findElement(By.css(".pl-6")).sendKeys("food")
    await driver.findElement(By.css(".pl-6")).sendKeys(Key.ENTER)
  })
})
