// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('nonexistentusersearch', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('nonexistentusersearch', async function() {
    // Test name: nonexistentusersearch
    // Step # | name | target | value | comment
    // 1 | open | https://connectco.netlify.app/ |  | 
    await driver.get("https://connectco.netlify.app/")
    // 2 | setWindowSize | 1552x832 |  | 
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    // 3 | click | css=.pl-6 |  | 
    await driver.findElement(By.css(".pl-6")).click()
    // 4 | type | css=.pl-6 | alin | 
    await driver.findElement(By.css(".pl-6")).sendKeys("alin")
    // 5 | sendKeys | css=.pl-6 | ${KEY_ENTER} | 
    await driver.findElement(By.css(".pl-6")).sendKeys(Key.ENTER)
    // 6 | mouseOver | css=.fi-rr-sun |  | 
    {
      const element = await driver.findElement(By.css(".fi-rr-sun"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 7 | mouseOut | css=.fi-rr-sun |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
