// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('unidentifiedKeywordsearching', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('unidentifiedKeywordsearching', async function() {
    await driver.get("https://connectco.netlify.app/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".pl-6")).click()
    await driver.findElement(By.css(".pl-6")).sendKeys("food")
    await driver.findElement(By.css(".pl-6")).sendKeys(Key.ENTER)
  })
})
