// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('similar blogs', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('similar blogs', async function() {
    await driver.get("http://localhost:5173/blog/blog-useTGxCeexDmgZwRlIJzzCT4")
    await driver.manage().window().setRect({ width: 1050, height: 652 })
    await driver.findElement(By.css(".flex-none > .w-full")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css("div:nth-child(2) > .flex > .w-full > .blog-title")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css("div:nth-child(14) > .flex > .w-full")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.close()
  })
})
