// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('edit_profile_successful', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('edit_profile_successful', async function() {
    // Test name: edit_profile_successful
    // Step # | name | target | value
    // 1 | open | http://localhost:5173/ | 
    await driver.get("http://localhost:5173/")
    // 2 | setWindowSize | 1058x804 | 
    await driver.manage().window().setRect({ width: 1058, height: 804 })
    // 3 | click | linkText=Sign In | 
    await driver.findElement(By.linkText("Sign In")).click()
    // 4 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 5 | type | name=email | ghorizeelj@gmail.com
    await driver.findElement(By.name("email")).sendKeys("ghorizeelj@gmail.com")
    // 6 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 7 | type | name=password | Password123New
    await driver.findElement(By.name("password")).sendKeys("Password123New")
    // 8 | click | css=.mt-14 | 
    await driver.findElement(By.css(".mt-14")).click()
    // 9 | click | css=.w-12 > .w-full | 
    await driver.findElement(By.css(".w-12 > .w-full")).click()
    // 10 | click | linkText=Settings | 
    await driver.findElement(By.linkText("Settings")).click()
    // 11 | click | linkText=Edit Profile | 
    await driver.findElement(By.linkText("Edit Profile")).click()
    // 12 | click | name=username | 
    await driver.findElement(By.name("username")).click()
    // 13 | type | name=username | zeel ghori user
    await driver.findElement(By.name("username")).sendKeys("zeel ghori user")
    // 14 | click | name=bio | 
    await driver.findElement(By.name("bio")).click()
    // 15 | type | name=bio | Hi, My name is Zeel.\nMy student ID is 202201287.
    await driver.findElement(By.name("bio")).sendKeys("Hi, My name is Zeel.\\nMy student ID is 202201287.")
    // 16 | click | name=youtube | 
    await driver.findElement(By.name("youtube")).click()
    // 17 | type | name=youtube | https://www.youtube.com/
    await driver.findElement(By.name("youtube")).sendKeys("https://www.youtube.com/")
    // 18 | click | name=facebook | 
    await driver.findElement(By.name("facebook")).click()
    // 19 | type | name=facebook | https://www.facebook.com/
    await driver.findElement(By.name("facebook")).sendKeys("https://www.facebook.com/")
    // 20 | click | name=twitter | 
    await driver.findElement(By.name("twitter")).click()
    // 21 | type | name=twitter | https://twitter.com
    await driver.findElement(By.name("twitter")).sendKeys("https://twitter.com")
    // 22 | click | name=github | 
    await driver.findElement(By.name("github")).click()
    // 23 | type | name=github | https://github.com/
    await driver.findElement(By.name("github")).sendKeys("https://github.com/")
    // 24 | click | name=instagram | 
    await driver.findElement(By.name("instagram")).click()
    // 25 | type | name=instagram | https://www.instagram.com/
    await driver.findElement(By.name("instagram")).sendKeys("https://www.instagram.com/")
    // 26 | click | name=website | 
    await driver.findElement(By.name("website")).click()
    // 27 | type | name=website | https://www.instagram.com/
    await driver.findElement(By.name("website")).sendKeys("https://www.instagram.com/")
    // 28 | click | css=.btn-dark | 
    await driver.findElement(By.css(".btn-dark")).click()
    // 29 | click | css=.relative > .w-12 | 
    await driver.findElement(By.css(".relative > .w-12")).click()
    // 30 | click | linkText=Profile | 
    await driver.findElement(By.linkText("Profile")).click()
    // 31 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
  })
})
