// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('edit_profile_unsuccessfull_invalid_links', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('edit_profile_unsuccessfull_invalid_links', async function() {
    // Test name: edit_profile_unsuccessfull_invalid_links
    // Step # | name | target | value
    // 1 | open | http://localhost:5173/ | 
    await driver.get("http://localhost:5173/")
    // 2 | setWindowSize | 1058x804 | 
    await driver.manage().window().setRect({ width: 1058, height: 804 })
    // 3 | click | linkText=Sign In | 
    await driver.findElement(By.linkText("Sign In")).click()
    // 4 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 5 | type | name=email | ghorizeelj@gmail.com
    await driver.findElement(By.name("email")).sendKeys("ghorizeelj@gmail.com")
    // 6 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 7 | type | name=password | Password123New
    await driver.findElement(By.name("password")).sendKeys("Password123New")
    // 8 | click | css=.mt-14 | 
    await driver.findElement(By.css(".mt-14")).click()
    // 9 | click | css=.w-12 > .w-full | 
    await driver.findElement(By.css(".w-12 > .w-full")).click()
    // 10 | click | linkText=Settings | 
    await driver.findElement(By.linkText("Settings")).click()
    // 11 | click | linkText=Edit Profile | 
    await driver.findElement(By.linkText("Edit Profile")).click()
    // 12 | click | name=youtube | 
    await driver.findElement(By.name("youtube")).click()
    // 13 | type | name=youtube | https://www.youtub
    await driver.findElement(By.name("youtube")).sendKeys("https://www.youtub")
    // 14 | click | css=.btn-dark | 
    await driver.findElement(By.css(".btn-dark")).click()
    // 15 | runScript | window.scrollTo(0,128.8000030517578) | 
    await driver.executeScript("window.scrollTo(0,128.8000030517578)")
    // 16 | click | name=youtube | 
    await driver.findElement(By.name("youtube")).click()
    // 17 | type | name=youtube | https://www.youtube.com/
    await driver.findElement(By.name("youtube")).sendKeys("https://www.youtube.com/")
    // 18 | click | name=facebook | 
    await driver.findElement(By.name("facebook")).click()
    // 19 | type | name=facebook | https://www.facebook
    await driver.findElement(By.name("facebook")).sendKeys("https://www.facebook")
    // 20 | click | css=.btn-dark | 
    await driver.findElement(By.css(".btn-dark")).click()
    // 21 | runScript | window.scrollTo(0,128.8000030517578) | 
    await driver.executeScript("window.scrollTo(0,128.8000030517578)")
    // 22 | click | name=facebook | 
    await driver.findElement(By.name("facebook")).click()
    // 23 | type | name=facebook | https://www.facebook.com/
    await driver.findElement(By.name("facebook")).sendKeys("https://www.facebook.com/")
    // 24 | click | css=.btn-dark | 
    await driver.findElement(By.css(".btn-dark")).click()
    // 25 | click | name=twitter | 
    await driver.findElement(By.name("twitter")).click()
    // 26 | type | name=twitter | https://twitter
    await driver.findElement(By.name("twitter")).sendKeys("https://twitter")
    // 27 | click | css=.btn-dark | 
    await driver.findElement(By.css(".btn-dark")).click()
    // 28 | mouseOver | css=.btn-dark | 
    {
      const element = await driver.findElement(By.css(".btn-dark"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 29 | mouseOut | css=.btn-dark | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 30 | click | name=twitter | 
    await driver.findElement(By.name("twitter")).click()
    // 31 | type | name=twitter | https://twitter.com
    await driver.findElement(By.name("twitter")).sendKeys("https://twitter.com")
    // 32 | click | name=github | 
    await driver.findElement(By.name("github")).click()
    // 33 | type | name=github | https://githom/
    await driver.findElement(By.name("github")).sendKeys("https://githom/")
    // 34 | click | css=.btn-dark | 
    await driver.findElement(By.css(".btn-dark")).click()
    // 35 | click | name=github | 
    await driver.findElement(By.name("github")).click()
    // 36 | click | name=github | 
    await driver.findElement(By.name("github")).click()
    // 37 | click | name=github | 
    await driver.findElement(By.name("github")).click()
    // 38 | click | css=.relative:nth-child(4) | 
    await driver.findElement(By.css(".relative:nth-child(4)")).click()
    // 39 | click | name=github | 
    await driver.findElement(By.name("github")).click()
    // 40 | type | name=github | https://github.com/
    await driver.findElement(By.name("github")).sendKeys("https://github.com/")
    // 41 | click | css=.btn-dark | 
    await driver.findElement(By.css(".btn-dark")).click()
    // 42 | click | name=instagram | 
    await driver.findElement(By.name("instagram")).click()
    // 43 | type | name=instagram | https://www.insta.com/
    await driver.findElement(By.name("instagram")).sendKeys("https://www.insta.com/")
    // 44 | click | css=.btn-dark | 
    await driver.findElement(By.css(".btn-dark")).click()
    // 45 | runScript | window.scrollTo(0,128.8000030517578) | 
    await driver.executeScript("window.scrollTo(0,128.8000030517578)")
    // 46 | click | name=instagram | 
    await driver.findElement(By.name("instagram")).click()
    // 47 | click | name=instagram | 
    await driver.findElement(By.name("instagram")).click()
    // 48 | type | name=instagram | https://www.instagram.com/
    await driver.findElement(By.name("instagram")).sendKeys("https://www.instagram.com/")
    // 49 | click | name=website | 
    await driver.findElement(By.name("website")).click()
    // 50 | type | name=website | https://agram.com/
    await driver.findElement(By.name("website")).sendKeys("https://agram.com/")
    // 51 | click | css=.btn-dark | 
    await driver.findElement(By.css(".btn-dark")).click()
  })
})
