// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Load_more_replies', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Load_more_replies', async function() {
    await driver.get("http://localhost:5173/blog/blog-useTGxCeexDmgZwRlIJzzCT4")
    await driver.manage().window().setRect({ width: 1050, height: 652 })
    await driver.findElement(By.css(".flex:nth-child(10) .w-10:nth-child(3) > .fi")).click()
    await driver.findElement(By.css("div:nth-child(6) .underline")).click()
    {
      const element = await driver.findElement(By.css("div:nth-child(6) .underline"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("div:nth-child(6) .text-dark-grey")).click()
    await driver.findElement(By.css(".p-2:nth-child(2)")).click()
    await driver.close()
  })
})
