// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('creating_comments', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('creating_comments', async function() {
    await driver.get("http://localhost:5173/blog/IndiaDZ-VeJWcIr78WjqXSRStB")
    await driver.manage().window().setRect({ width: 1050, height: 652 })
    await driver.findElement(By.linkText("Sign In")).click()
    await driver.findElement(By.name("email")).sendKeys("siddhantg86@gmail.com")
    await driver.findElement(By.name("password")).sendKeys("Siddhant@186")
    await driver.findElement(By.css(".mt-14")).click()
    await driver.findElement(By.css("div:nth-child(4) .w-full > .blog-title")).click()
    await driver.findElement(By.css(".flex:nth-child(10) .w-10:nth-child(3) > .fi")).click()
    await driver.findElement(By.css(".input-box")).click()
    await driver.findElement(By.css(".input-box")).sendKeys("comment 1")
    await driver.findElement(By.css(".btn-dark")).click()
    await driver.findElement(By.css(".right-0")).click()
    await driver.findElement(By.css(".object-cover")).click()
    await driver.findElement(By.css(".font-bold")).click()
    await driver.findElement(By.css(".my-12")).click()
    {
      const element = await driver.findElement(By.css(".my-12"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
  })
})
