// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('edit_profile_bio_big', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('edit_profile_bio_big', async function() {
    // Test name: edit_profile_bio_big
    // Step # | name | target | value
    // 1 | open | http://localhost:5173/ | 
    await driver.get("http://localhost:5173/")
    // 2 | setWindowSize | 1062x804 | 
    await driver.manage().window().setRect({ width: 1062, height: 804 })
    // 3 | click | linkText=Sign In | 
    await driver.findElement(By.linkText("Sign In")).click()
    // 4 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 5 | type | name=email | ghorizeelj@gmail.com
    await driver.findElement(By.name("email")).sendKeys("ghorizeelj@gmail.com")
    // 6 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 7 | type | name=password | Password123New
    await driver.findElement(By.name("password")).sendKeys("Password123New")
    // 8 | click | css=.fi-rr-eye-crossed | 
    await driver.findElement(By.css(".fi-rr-eye-crossed")).click()
    // 9 | click | css=.mt-14 | 
    await driver.findElement(By.css(".mt-14")).click()
    // 10 | mouseOver | css=.tag:nth-child(4) | 
    {
      const element = await driver.findElement(By.css(".tag:nth-child(4)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 11 | click | css=.w-12 > .w-full | 
    await driver.findElement(By.css(".w-12 > .w-full")).click()
    // 12 | click | linkText=Settings | 
    await driver.findElement(By.linkText("Settings")).click()
    // 13 | click | linkText=Edit Profile | 
    await driver.findElement(By.linkText("Edit Profile")).click()
    // 14 | click | name=bio | 
    await driver.findElement(By.name("bio")).click()
    // 15 | click | css=.flex-col | 
    await driver.findElement(By.css(".flex-col")).click()
    // 16 | type | name=bio | But how many people actually read professional bios, anyway?\n\nWell, I can tell you that I get a number of “Someone has viewed your profile” notificat\n
    await driver.findElement(By.name("bio")).sendKeys("But how many people actually read professional bios, anyway?\\n\\nWell, I can tell you that I get a number of “Someone has viewed your profile” notificat\\n")
    // 17 | click | css=.btn-dark | 
    await driver.findElement(By.css(".btn-dark")).click()
    // 18 | click | css=.object-cover | 
    await driver.findElement(By.css(".object-cover")).click()
    // 19 | click | linkText=Profile | 
    await driver.findElement(By.linkText("Profile")).click()
    // 20 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 21 | click | css=.h-full | 
    await driver.findElement(By.css(".h-full")).click()
    // 22 | click | css=.font-bold | 
    await driver.findElement(By.css(".font-bold")).click()
  })
})
